# Google Cloud Run configuration
# This file helps with source-based deployments

runtime: python311

# Environment variables
env_variables:
  PORT: 8080
  PYTHONPATH: /app
  MONGODB_URL: mongodb+srv://shaaz:Shaaz123@cluster0.hp19dzy.mongodb.net/resume_matcher
  MONGODB_MIN_CONNECTIONS: 5
  MONGODB_MAX_CONNECTIONS: 20
  MONGODB_SERVER_SELECTION_TIMEOUT_MS: 10000
  MONGODB_CONNECT_TIMEOUT_MS: 15000
  MONGODB_SOCKET_TIMEOUT_MS: 30000
  LOG_LEVEL: INFO
  DEBUG: False
  MAX_FILE_SIZE_MB: 10
  ALLOWED_FILE_TYPES: pdf,doc,docx,txt

# Resource settings
automatic_scaling:
  min_instances: 0
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 2

# Network settings
network:
  session_affinity: false