# Cloud Build configuration for AuraHire AI using Buildpacks (no Docker)
steps:
  # Build and deploy using gcloud run deploy (uses buildpacks automatically)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aurahire-ai'
      - '--source=.'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=100'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=MONGODB_URL=mongodb+srv://shaaz:Shaaz123@cluster0.hp19dzy.mongodb.net/resume_matcher,MONGODB_MIN_CONNECTIONS=5,MONGODB_MAX_CONNECTIONS=20,MONGODB_SERVER_SELECTION_TIMEOUT_MS=5000,MONGODB_CONNECT_TIMEOUT_MS=10000,MONGODB_SOCKET_TIMEOUT_MS=20000,LOG_LEVEL=INFO,DEBUG=False,MAX_FILE_SIZE_MB=10,ALLOWED_FILE_TYPES=pdf,doc,docx,txt'

# Build options
options:
  # Use higher CPU for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Increase timeout for large builds
  timeout: '1200s'